name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Find path for app and copy .test.env
      run: |
          pwd
          cp .github/workflows/.test.env .env

          ls -la

          echo ------
          cat .env

    - name: Install Prebuilt MPR and just spring cli
      run: |
        wget -qO - 'https://proget.makedeb.org/debian-feeds/prebuilt-mpr.pub' | gpg --dearmor | sudo tee /usr/share/keyrings/prebuilt-mpr-archive-keyring.gpg 1> /dev/null
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/prebuilt-mpr-archive-keyring.gpg] https://proget.makedeb.org prebuilt-mpr $(lsb_release -cs)" | sudo tee /etc/apt/sources.list.d/prebuilt-mpr.list
        sudo apt update

        sudo apt install just

    - name: Install jdk 17 and spring cli
      run: |
        sudo apt install -y unzip openjdk-17-jdk
        sudo update-java-alternatives -s java-1.17.0-openjdk-amd64
        

        wget https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-cli/3.0.6/spring-boot-cli-3.0.6-bin.zip 
        unzip spring-boot-cli-3.0.6-bin.zip

    - name: Install assert.sh
      run: |
        mkdir lib

        cd lib

        git clone https://github.com/torokmark/assert.sh.git

        cd assert.sh 
        rm -rf .git

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test app
      run: |
        export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64/
        export PATH=$PATH:$JAVA_HOME

        export SPRING_HOME=$(pwd)/spring-3.0.6
        export PATH=$SPRING_HOME/bin:$PATH

        just test
